### ISSUE TITLE
Boost.Python NumPy support

### ISSUE THREAD

**Issue by lucas-bremond** [personalrobotics/boost_numpy_eigen#1]
Hi!

It seems that https://github.com/ndarray/Boost.NumPy is deprecated,
as NumPy support is now natively supported by **Boost.Python**.

Do you have any plans to update this library accordingly?

**Comment by jslee02** [comment]
Thanks for the heads up! That is true. We [updated](https://github.com/personalrobotics/boost_numpy_eigen_legacy/pull/8) this library to be compatible with Boost.Python (> 1.63) for the reason you posted but later [removed](https://github.com/personalrobotics/boost_numpy_eigen_legacy/pull/12) the compatibility code because this library doesn't actually have dependency on the NumPy support of Boost.Python. That said, [this library already works with the newer version of Boost.Python](https://travis-ci.org/personalrobotics/boost_numpy_eigen/jobs/416953050#L1666).

**Comment by jslee02** [comment]
Let me close this issue. Feel free to reopen if you have further concerns!
